### ISSUE TITLE
Parser fails on type ascription

### ISSUE THREAD

**Issue by abailly** [qfpl/hpython#158]
While parser now supports type annotations in various places, there is one use it chokes on:

```
    result : List[HistoryLine] = []
```

BTW, thank you for this great work!

**Comment by LightAndLight** [comment]
Thanks for checking it out :) Assignment type annotations were introduced in Python 3.6, so it's expected that we can't yet parse them.

Modular support for newer Python versions is our next big milestone

**Comment by abailly** [comment]
👍 Should I close this issue ATM?

**Comment by LightAndLight** [comment]
Done
