### ISSUE TITLE
Conversion to `NonEmpty` rather than list for types which should do it naturally

### ISSUE THREAD

**Issue by ldobrek** [qfpl/hpython#168]
Could we get `Foldable1` on types which can implement it.
For instance for `Block` it would be nice to be able to convert it to `NonEmpty Statement` rather than `[Statement]`. I have very little idea about lenses but I understand that in order to use `toNonEmptyOf` the type should implement `Foldable1` and/or `Traversable1` rather then `Foldable` as it does now. 

The same I guess applies to `CommaSep1` and `CommaSep1'`

**Comment by LightAndLight** [comment]
Good suggestion, I'll get on it.

**Comment by LightAndLight** [comment]
I've added `Foldable1`/`Traversable1` instances for `CommaSep` and `CommaSep1`, and I've added a `HasStatements1` class which has `_Statements1 :: Traversal1 ...`. Currently `Statement` and `Block` are instances. Are there any other datatypes that you think should get instances?

**Comment by ldobrek** [comment]
Thank you that was quick. I looked and I don't see anything else. modules can be empty so the only thing is Suite but this is strange again cause it could be just a SmallStatement. This is great, thank you again.

**Comment by LightAndLight** [comment]
Fixed in https://hackage.haskell.org/package/hpython-0.3
