### ISSUE TITLE
hpython.nix has version 0.2

### ISSUE THREAD

**Issue by MarisaKirisame** [qfpl/hpython#171]
this is a line in hpython.nix:
> version = "0.2";

however, hackage show that the latest versions is 0.3. I am new to nix so what is happening here?

**Comment by LightAndLight** [comment]
I forgot to update the nix expressions. I'll spend time today getting this and #172 working for you

**Comment by LightAndLight** [comment]
Sorry for not getting back to you, we've had a busy past couple of months.
I've been moved to a different project for the time being, but if I get
some spare time this week I'll fix this up for you.

**Comment by MarisaKirisame** [comment]
thank you!

**Comment by LightAndLight** [comment]
Master now builds with whichever version of nixpkgs I'm running. Let me know if you have trouble with it.
