### ISSUE TITLE
How to implement decorators parsing?

### ISSUE THREAD

**Issue by abailly** [qfpl/hpython#55]
I am trying to implement parsing for python 3 decorators and struggling (see http://python-3-patterns-idioms-test.readthedocs.io/en/latest/PythonDecorators.html for details...).

What I have so far is that I've defined:

```
data Decorator v a 
  = Decorator (Indents a) (Ident v a)
  -- ^ '@' <ident>
  deriving (Eq, Show, Functor, Foldable, Traversable)
```

The `Decorator` is parsed using a `TkAt` token that contains the string for the decorator's name (I am only tackling argument less decorators ATM):

```
    parseDecoratorIdentifier :: Parser ann (Ident '[] ann)
    parseDecoratorIdentifier = do
      curTk <- currentToken
      case curTk of
        TkAt s ann -> do
          Parser $ consumed ann
          pure $ MkIdent ann s []
        _ -> Parser . throwError $ ExpectedIdentifier curTk

    maybeDecorator :: Parser ann (Maybe (Decorator '[] ann))
    maybeDecorator = optional (Decorator <$> 
      indents <*> parseDecoratorIdentifier)
```

Then I've augmented `FunDef` with a `Maybe (Decorator v a)` field.

```
compoundStatement :: Parser ann (CompoundStatement '[] ann)
compoundStatement =
  fundef <!> ....
    where
     fundef =
      (\dec a (tkDef, defSpaces) -> Fundef dec a (pyTokenAnn tkDef) (NonEmpty.fromList defSpaces)) <$>
      maybeDecorator <*>
      indents <*>
      token space (TkDef ()) <*>
.....
```

Now when I try to parse `"@decorate\ndef fun(a:str) ->  int:\n    return 1"` I got the following error:

```
     ┏━━ test/Helpers.hs ━━━
    40 ┃ doParse :: (Show ann, Monad m) => ann -> Parser ann a -> Nested ann -> PropertyT m a
    41 ┃ doParse initial pa input = do
    42 ┃   let res = runParser initial pa input
    43 ┃   case res of
    44 ┃     Left err -> do
    45 ┃       annotateShow err
       ┃       │ UnexpectedEndOfLine (Caret (Columns 0 0) "@decorate\n")
    46 ┃       failure
       ┃       ^^^^^^^
    47 ┃     Right a -> pure a
```

So the decorator needs to handle the newline and be at the same indentation level than the `def` it is attached to. How do I implement that in `hpython`?

**Comment by LightAndLight** [comment]
Hi @abailly, sorry I didn't see this earlier. I actually merged decorator support yesterday.

But the problem you encountered is that you didn't update the lexer. We have a multi-stage parsing process: Tokenize -> Join Lines -> Indentation -> Parse -> AST.

The lexer can currently be found in `Language.Python.Internal.Lexer`.

**Comment by abailly** [comment]
Ah! I managed to get something working, will merge your stuff then :)
